// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/activity/feed": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch the user's personalized activity feed from friends and followed users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activity"
                ],
                "summary": "Get Activity Feed",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/activity.ActivityItem"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/callback": {
            "post": {
                "description": "OAuth callback endpoint for authentication providers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Auth Callback",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/signout": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Sign out the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign Out",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/user": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch the current authenticated user's profile",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get Current User",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.UserProfile"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/chen/chat": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Send a message to Chen AI and get a music-aware response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chen"
                ],
                "summary": "Chat with Chen AI",
                "parameters": [
                    {
                        "description": "User message and conversation history",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chen.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chen.ChatResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/chen/conversation": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch the Chen AI chat conversation history with music context",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chen"
                ],
                "summary": "Get Conversation History",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chen.ConversationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/compatibility": {
            "get": {
                "description": "Check music compatibility with another user (coming soon)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "compatibility"
                ],
                "summary": "Get Music Compatibility",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/friends": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch the current user's friend list with current activity and compatibility scores",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Get Friends List",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/friends.Friend"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/friends/accept": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Accept a pending friend request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Accept Friend Request",
                "parameters": [
                    {
                        "description": "Friendship ID to accept",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/friends.FriendshipActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/friends/add": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Send a friend request to another user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Add Friend",
                "parameters": [
                    {
                        "description": "Username of user to add",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/friends.AddFriendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/friends/search": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Search for users by username or user_tag",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Search Users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query (username or user_tag)",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/friends.SearchResult"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/messages/threads": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch all active message threads for the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "List Message Threads",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/messages.ThreadSummary"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/messages/{friendID}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch all messages in a conversation with a specific friend",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Get Message Thread",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Friend's user ID",
                        "name": "friendID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/messages.ThreadResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/notifications": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch all notifications for the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "List Notifications",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/notifications.NotificationListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/notifications/unread-count": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get the number of unread notifications for the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Get Unread Notification Count",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/notifications/{id}/read": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Mark a specific notification as read",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Mark Notification as Read",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notification ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/payments": {
            "get": {
                "description": "Payment system endpoint (coming soon)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Get Payments Info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/profile/stats": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch listening statistics for the current user (minutes listened, artists, top genre)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get Profile Stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/profile.ProfileStats"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/profile/top-artists": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch the user's most played artists",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get Top Artists",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/profile.ProfileTopArtist"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/profile/top-tracks": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch the user's most played tracks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get Top Tracks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/profile.ProfileTopTrack"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/profile/users/{userID}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch a user's public profile with their stats, recent activity, and relationship status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get Public User Profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/profile.PublicProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reactions/comments": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Add a comment on an activity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reactions"
                ],
                "summary": "Create Comment",
                "parameters": [
                    {
                        "description": "Comment content",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reactions.createCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/reactions.commentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reactions/comments/{activityID}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch all comments on a specific activity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reactions"
                ],
                "summary": "Get Comments on Activity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Activity ID",
                        "name": "activityID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/reactions.commentResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reactions/engagement": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get comments and reactions counts for multiple activities",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reactions"
                ],
                "summary": "Get Engagement Metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated list of activity IDs",
                        "name": "activity_ids",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/reactions.engagementResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reactions/toggle": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Add or remove a reaction (love, fire, headphones) on an activity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reactions"
                ],
                "summary": "Toggle Reaction",
                "parameters": [
                    {
                        "description": "Activity ID and reaction type (love, fire, headphones)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reactions.toggleReactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/spotify/connect": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Connect or refresh Spotify connection with access tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spotify"
                ],
                "summary": "Connect Spotify Account",
                "parameters": [
                    {
                        "description": "Spotify connection tokens",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/spotify.ConnectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/spotify/now-playing": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch the currently playing track from user's Spotify",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spotify"
                ],
                "summary": "Get Currently Playing Track",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/spotify.ActivityItem"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/spotify/recent": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch user's recently played tracks from Spotify",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spotify"
                ],
                "summary": "Get Recent Tracks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/spotify.ActivityItem"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/spotify/top-artists": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch user's top artists from Spotify",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spotify"
                ],
                "summary": "Get Top Artists",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/spotify/top-tracks": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Fetch user's top tracks from Spotify",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spotify"
                ],
                "summary": "Get Top Tracks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/spotify.ActivityItem"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "activity.ActivityItem": {
            "type": "object",
            "properties": {
                "album_art_url": {
                    "type": "string"
                },
                "album_name": {
                    "type": "string"
                },
                "artist_name": {
                    "type": "string"
                },
                "avatar_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_playing": {
                    "type": "boolean"
                },
                "platform": {
                    "type": "string"
                },
                "played_at": {
                    "type": "string"
                },
                "preview_url": {
                    "type": "string"
                },
                "spotify_url": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "track_id": {
                    "type": "string"
                },
                "track_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.UserProfile": {
            "type": "object",
            "properties": {
                "avatar_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_premium": {
                    "type": "boolean"
                },
                "user_tag": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "chen.ChatRequest": {
            "type": "object",
            "properties": {
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/chen.ConversationMessage"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "chen.ChatResponse": {
            "type": "object",
            "properties": {
                "reply": {
                    "type": "string"
                }
            }
        },
        "chen.ConversationMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "chen.ConversationResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/chen.ConversationMessage"
                    }
                }
            }
        },
        "friends.ActivityItem": {
            "type": "object",
            "properties": {
                "album_art_url": {
                    "type": "string"
                },
                "album_name": {
                    "type": "string"
                },
                "artist_name": {
                    "type": "string"
                },
                "avatar_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_playing": {
                    "type": "boolean"
                },
                "platform": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "track_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "friends.AddFriendRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "friends.Friend": {
            "type": "object",
            "properties": {
                "avatar_id": {
                    "type": "string"
                },
                "compatibility": {
                    "type": "integer"
                },
                "current_track": {
                    "$ref": "#/definitions/friends.ActivityItem"
                },
                "id": {
                    "type": "string"
                },
                "is_online": {
                    "type": "boolean"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "friends.FriendshipActionRequest": {
            "type": "object",
            "required": [
                "friendship_id"
            ],
            "properties": {
                "friendship_id": {
                    "type": "string"
                }
            }
        },
        "friends.SearchResult": {
            "type": "object",
            "properties": {
                "avatar_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "relationship_status": {
                    "type": "string"
                },
                "user_tag": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "messages.MessageFriend": {
            "type": "object",
            "properties": {
                "avatar_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "messages.MessageItem": {
            "type": "object",
            "properties": {
                "audio_duration_ms": {
                    "type": "integer"
                },
                "audio_url": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_mine": {
                    "type": "boolean"
                },
                "message_type": {
                    "type": "string"
                },
                "read_at": {
                    "type": "string"
                },
                "recipient_id": {
                    "type": "string"
                },
                "sender_id": {
                    "type": "string"
                },
                "track_metadata": {
                    "$ref": "#/definitions/messages.TrackMetadata"
                }
            }
        },
        "messages.ThreadResponse": {
            "type": "object",
            "properties": {
                "friend": {
                    "$ref": "#/definitions/messages.MessageFriend"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/messages.MessageItem"
                    }
                }
            }
        },
        "messages.ThreadSummary": {
            "type": "object",
            "properties": {
                "friend": {
                    "$ref": "#/definitions/messages.MessageFriend"
                },
                "lastMessage": {
                    "$ref": "#/definitions/messages.MessageItem"
                },
                "unreadCount": {
                    "type": "integer"
                }
            }
        },
        "messages.TrackMetadata": {
            "type": "object",
            "properties": {
                "activity_id": {
                    "type": "string"
                },
                "album_art_url": {
                    "type": "string"
                },
                "album_name": {
                    "type": "string"
                },
                "artist_name": {
                    "type": "string"
                },
                "spotify_url": {
                    "type": "string"
                },
                "track_id": {
                    "type": "string"
                },
                "track_name": {
                    "type": "string"
                }
            }
        },
        "notifications.NotificationActor": {
            "type": "object",
            "properties": {
                "avatar_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "notifications.NotificationItem": {
            "type": "object",
            "properties": {
                "actor": {
                    "$ref": "#/definitions/notifications.NotificationActor"
                },
                "body": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "entity_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "read_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "notifications.NotificationListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/notifications.NotificationItem"
                    }
                },
                "unreadCount": {
                    "type": "integer"
                }
            }
        },
        "profile.ProfileStats": {
            "type": "object",
            "properties": {
                "artistsPlayed": {
                    "type": "integer"
                },
                "minutesListened": {
                    "type": "integer"
                },
                "topGenre": {
                    "type": "string"
                }
            }
        },
        "profile.ProfileTopArtist": {
            "type": "object",
            "properties": {
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "playCount": {
                    "type": "integer"
                }
            }
        },
        "profile.ProfileTopTrack": {
            "type": "object",
            "properties": {
                "artist": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "playCount": {
                    "type": "integer"
                }
            }
        },
        "profile.PublicProfileRelationship": {
            "type": "object",
            "properties": {
                "canMessage": {
                    "type": "boolean"
                },
                "friendshipId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "profile.PublicProfileResponse": {
            "type": "object",
            "properties": {
                "nowPlaying": {
                    "$ref": "#/definitions/profile.PublicProfileTrack"
                },
                "recentTracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/profile.PublicProfileTrack"
                    }
                },
                "relationship": {
                    "$ref": "#/definitions/profile.PublicProfileRelationship"
                },
                "stats": {
                    "$ref": "#/definitions/profile.PublicProfileStats"
                },
                "topArtists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/profile.ProfileTopArtist"
                    }
                },
                "topTracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/profile.ProfileTopTrack"
                    }
                },
                "user": {
                    "$ref": "#/definitions/profile.PublicProfileUser"
                }
            }
        },
        "profile.PublicProfileStats": {
            "type": "object",
            "properties": {
                "artistsPlayed": {
                    "type": "integer"
                },
                "minutesListened": {
                    "type": "integer"
                },
                "topGenre": {
                    "type": "string"
                }
            }
        },
        "profile.PublicProfileTrack": {
            "type": "object",
            "properties": {
                "album_art_url": {
                    "type": "string"
                },
                "album_name": {
                    "type": "string"
                },
                "artist_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_playing": {
                    "type": "boolean"
                },
                "platform": {
                    "type": "string"
                },
                "played_at": {
                    "type": "string"
                },
                "preview_url": {
                    "type": "string"
                },
                "spotify_url": {
                    "type": "string"
                },
                "track_id": {
                    "type": "string"
                },
                "track_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "profile.PublicProfileUser": {
            "type": "object",
            "properties": {
                "avatar_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "user_tag": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "reactions.ReactionType": {
            "type": "string",
            "enum": [
                "love",
                "fire",
                "headphones"
            ],
            "x-enum-varnames": [
                "reactionLove",
                "reactionFire",
                "reactionHeadphones"
            ]
        },
        "reactions.commentResponse": {
            "type": "object",
            "properties": {
                "avatar_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "parent_comment_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "reactions.createCommentRequest": {
            "type": "object",
            "required": [
                "activity_id",
                "content"
            ],
            "properties": {
                "activity_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "parent_comment_id": {
                    "type": "string"
                }
            }
        },
        "reactions.engagementResponse": {
            "type": "object",
            "properties": {
                "commentCount": {
                    "type": "integer"
                },
                "reactions": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "userReactions": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                }
            }
        },
        "reactions.toggleReactionRequest": {
            "type": "object",
            "required": [
                "activity_id",
                "reaction_type"
            ],
            "properties": {
                "activity_id": {
                    "type": "string"
                },
                "reaction_type": {
                    "$ref": "#/definitions/reactions.ReactionType"
                }
            }
        },
        "spotify.ActivityItem": {
            "type": "object",
            "properties": {
                "album_art_url": {
                    "type": "string"
                },
                "album_name": {
                    "type": "string"
                },
                "artist_name": {
                    "type": "string"
                },
                "avatar_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_playing": {
                    "type": "boolean"
                },
                "platform": {
                    "type": "string"
                },
                "preview_url": {
                    "type": "string"
                },
                "spotify_url": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "track_id": {
                    "type": "string"
                },
                "track_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "spotify.ConnectRequest": {
            "type": "object",
            "required": [
                "access_token",
                "expires_in",
                "refresh_token"
            ],
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        }
    }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Chen API",
	Description:      "API documentation for the Chen, a music compatibility and social platform.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
